### PR TITLE
OCMock.h: add explicit cast to `id` in `OCMVerifyAll*()` methods.

### PR DESCRIPTION
**Pull request by mkimi-lightricks**

### CODE REVIEW

**Comment by mkimi-lightricks** [comment]
@StatusReport please CR.

**Comment by barakwei** [comment]
@StatusReport perms please

**Comment by StatusReport** [comment]
@mkimi-lightricks I'd wrap `mock` and `delay` with parens while you're at it.

@barakwei done.

**Comment by mkimi-lightricks** [comment]
@StatusReport done.

**Comment by StatusReport** [comment]
@barakwei we probably want to set CircleCI here as well.

**Pull request merged**
