### PR TITLE
CircleCI: initial commit.

### PR DESCRIPTION
**Pull request by barakwei**

### CODE REVIEW

**Comment by barakwei** [comment]
@StatusReport do you see the point in fixing the test to match our changes?

**Comment by StatusReport** [comment]
@barakwei yes, if we removed this functionality from OCMock.

**Comment by StatusReport** [comment]
We can also see what happens when we bring it back - I think they fixed the issue in the runtime since iOS 9 but I'm not sure.

**Comment by barakwei** [comment]
IIRC when I brought it back there was a very weird crash deep in ReactiveObjC.

**Comment by StatusReport** [comment]
So let's remove these tests as well.

**Comment by barakwei** [comment]
@StatusReport PTAL

**Pull request merged**
